version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    command: ["/app/oia"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    command: ["nginx", "-g", "daemon off;"]